# Config file for CelebA dataset (200k)

output_dir: '/home/whh/Experiments/StyleGAN/FFHQ128/sample_ffhq_128_affine_false'
structure: 'linear'
device_id: ('3')
checkpoint_factor: 4
feedback_factor: 4
dataset:
  img_dir: '/home/whh/data/FFHQ128x128'
  folder: True
  resolution: 128
sched:
  epochs: [8,16,32,32,64,64]
