# Config file for CelebA dataset (200k)

output_dir: '/home/whh/Experiments/StyleGAN/color_symbol_7k/test30' #'/data/hzh/checkpoints/StyleGAN.pytorch/ckp_celeba_6'
structure: 'linear'
device_id: ('4')
dataset:
  img_dir: '/home/whh/data/color_symbol_7k' #'/home/hzh/data/img_align_celeba'
  folder: False
  resolution: 128
sched:
  epochs: [60,120,120,120,120,240]
